SystemOrganization addCategory: #'GToolkit-Playground'!
SystemOrganization addCategory: 'GToolkit-Playground-Announcements'!
SystemOrganization addCategory: 'GToolkit-Playground-Commands'!
SystemOrganization addCategory: 'GToolkit-Playground-Model'!
SystemOrganization addCategory: 'GToolkit-Playground-Obsolete'!
SystemOrganization addCategory: 'GToolkit-Playground-Page'!
SystemOrganization addCategory: 'GToolkit-Playground-Snippet - Looks'!
SystemOrganization addCategory: 'GToolkit-Playground-Snippet - Model'!
SystemOrganization addCategory: 'GToolkit-Playground-Snippet - Stencils'!
SystemOrganization addCategory: 'GToolkit-Playground-Snippet - UI'!
