SystemOrganization addCategory: #'GToolkit-Playground-Brick'!
SystemOrganization addCategory: 'GToolkit-Playground-Brick-Page'!
SystemOrganization addCategory: 'GToolkit-Playground-Brick-Snippet'!
SystemOrganization addCategory: 'GToolkit-Playground-Brick-Snippet - Looks'!
SystemOrganization addCategory: 'GToolkit-Playground-Brick-Snippet - Model'!
SystemOrganization addCategory: 'GToolkit-Playground-Brick-Snippet - Stencils'!
SystemOrganization addCategory: 'GToolkit-Playground-Brick-Snippet - UI'!
